import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

test('admin data archive destination form is rendered by React from request events', () => {
  const html = readFileSync('admin.html', 'utf8');
  const main = readFileSync('src/admin-app/main.js', 'utf8');
  const destinationForm = readFileSync('src/admin-app/data-archive-destination-form.js', 'utf8');
  const saveEndpoint = html.match(/async function adminSaveDataArchiveEndpointFromReact\(detail\) \{[\s\S]*?async function adminRunArchiveExport/)?.[0];
  const initAdmin = html.match(/function initAdmin\(\) \{[\s\S]*?\$\('adminCreateForm'\)\.addEventListener/)?.[0];

  assert.match(html, /id="adminDataArchiveDestinationFormReactApp"/);
  assert.doesNotMatch(html, /id="dxEndpointForm"|id="dxEndpointId"|id="dxEndpointLabel"|id="dxEndpointUrl"|id="dxAuthHeader"|id="dxAuthPrefix"|id="dxAuthToken"|id="dxAuthTokenClear"|id="dxEndpointActive"|id="dxEndpointSave"|id="dxEndpointCancel"/);
  assert.doesNotMatch(html, /function resetDataArchiveEndpointForm|async function adminSaveDataArchiveEndpoint\(e\)/);
  assert.match(html, /function setDataArchiveEndpointForm\(destination\) \{[\s\S]*gvdg:admin-data-archive-destination-form-edit/);
  assert.ok(saveEndpoint);
  assert.match(saveEndpoint, /adminApi\(path, \{ method, body \}\)/);
  assert.match(saveEndpoint, /gvdg:admin-data-archive-destination-save-result/);
  assert.match(saveEndpoint, /detail: \{ ok: false, requestId, message \}/);
  assert.match(saveEndpoint, /adminLoadDataArchiveDestinations\(\)/);
  assert.doesNotMatch(saveEndpoint, /dxEndpointLabel|dxEndpointUrl|dxAuthHeader|dxAuthPrefix|dxAuthToken|dxAuthTokenClear|dxEndpointActive|\$\('dxEndpoint/);
  assert.ok(initAdmin);
  assert.match(initAdmin, /gvdg:admin-data-archive-destination-save-request/);
  assert.match(initAdmin, /adminSaveDataArchiveEndpointFromReact\(event\.detail \|\| \{\}\)/);
  assert.doesNotMatch(initAdmin, /\$\('dxEndpointForm'\)\.addEventListener|\$\('dxEndpointCancel'\)\.addEventListener/);
  assert.match(main, /import \{ AdminDataArchiveDestinationForm \} from "\.\/data-archive-destination-form\.js"/);
  assert.match(main, /const dataArchiveDestinationFormMount = document\.getElementById\("adminDataArchiveDestinationFormReactApp"\)/);
  assert.match(main, /createRoot\(dataArchiveDestinationFormMount\)\.render\(h\(AdminDataArchiveDestinationForm\)\)/);
  assert.match(destinationForm, /export function AdminDataArchiveDestinationForm/);
  assert.match(destinationForm, /formRef = React\.useRef\(null\)/);
  assert.match(destinationForm, /const \[notice, setNotice\] = React\.useState\(""\)/);
  assert.match(destinationForm, /data-react-admin-data-archive-destination-form/);
  assert.match(destinationForm, /gvdg:admin-data-archive-destination-form-edit/);
  assert.match(destinationForm, /gvdg:admin-data-archive-destination-save-request/);
  assert.match(destinationForm, /gvdg:admin-data-archive-destination-save-result/);
  assert.match(destinationForm, /scrollIntoView\(\{ block: "start" \}\)/);
  assert.match(destinationForm, /className: "admin-form admin-data-archive-destination-form"/);
  assert.match(destinationForm, /className: "al-note err"/);
  assert.match(destinationForm, /role: "alert"/);
  assert.match(destinationForm, /id: "dxEndpointForm"/);
  assert.match(destinationForm, /id: "dxEndpointLabel"/);
  assert.match(destinationForm, /id: "dxEndpointUrl"/);
  assert.match(destinationForm, /id: "dxAuthTokenClear"/);
  assert.match(destinationForm, /id: "dxEndpointActive"/);
  assert.match(destinationForm, /busy \? "Saving\.\.\." : form\.id \? "Save destination" : "Add destination"/);
  assert.match(destinationForm, /className: "register-addon admin-data-archive-destination-toggle"/);
  assert.match(html, /\.admin-data-archive-destination-form \{ scroll-margin-top: 5\.5rem; \}/);
  assert.match(html, /\.admin-form \.admin-data-archive-destination-toggle \{/);
  assert.doesNotMatch(destinationForm, /innerHTML|insertAdjacentHTML|replaceChildren|document\.createElement|querySelector|classList|textContent\s*=|☰|✕|🔒|🌙|☀️|🏆|⚠|⏱|—/);
});
