import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

test('admin page chrome is rendered by the admin React bundle', () => {
  const html = readFileSync('admin.html', 'utf8');
  const main = readFileSync('src/admin-app/main.js', 'utf8');
  const chrome = readFileSync('src/admin-app/page-chrome.js', 'utf8');

  assert.match(html, /id="adminReactPageChromeApp"/);
  assert.match(html, /<script type="module" src="admin-app\/admin-app\.js"><\/script>/);
  assert.doesNotMatch(html, /<header>[\s\S]*class="menu-toggle"/);
  assert.doesNotMatch(html, /class="theme-icon"|const themeToggle|const menuToggle|themeIcon\.textContent|document\.querySelector\('\.menu-toggle'\)|document\.querySelector\('header'\)|document\.querySelectorAll\('\.logout-link'\)/);
  assert.match(main, /import \{ AdminPageChrome \} from "\.\/page-chrome\.js"/);
  assert.match(main, /const pageChromeMount = document\.getElementById\("adminReactPageChromeApp"\)/);
  assert.match(main, /createRoot\(pageChromeMount\)\.render\(h\(AdminPageChrome\)\)/);
  assert.match(chrome, /export function AdminPageChrome/);
  assert.match(chrome, /data-react-admin-chrome/);
  assert.match(chrome, /aria-expanded/);
  assert.match(chrome, /aria-current/);
  assert.match(chrome, /aria-pressed/);
  assert.match(chrome, /className: current \? "active" : undefined/);
  assert.match(chrome, /Menu, MoonStar, Sun, X/);
  assert.match(chrome, /window\.requestAnimationFrame\(update\)/);
  assert.match(chrome, /localStorage\.getItem\("theme"\)/);
  assert.match(chrome, /localStorage\.setItem\("theme", theme\)/);
  assert.match(chrome, /sessionStorage\.removeItem\(key\)/);
  assert.doesNotMatch(chrome, /innerHTML|insertAdjacentHTML|replaceChildren|document\.createElement|querySelector|classList|textContent\s*=|☰|✕|🌙|☀️/);
});

test('admin order badge updates through React instead of DOM text mutation', () => {
  const html = readFileSync('admin.html', 'utf8');
  const main = readFileSync('src/admin-app/main.js', 'utf8');
  const nav = readFileSync('src/admin-app/navigation.js', 'utf8');
  const badge = readFileSync('src/admin-app/orders-badge.js', 'utf8');
  const setBadge = html.match(/function setOrdersBadge\(n\) \{[\s\S]*?\n        \}/)?.[0];

  assert.match(html, /id="adminNavigationReactApp"/);
  assert.doesNotMatch(html, /id="ordersBadgeReactApp"/);
  assert.doesNotMatch(html, /id="ordersBadge" class="orders-badge" hidden/);
  assert.ok(setBadge);
  assert.match(setBadge, /window\.__gvdgAdminOrdersBadgeCount = count/);
  assert.match(setBadge, /new CustomEvent\('gvdg:admin-orders-badge', \{ detail: \{ count \} \}\)/);
  assert.doesNotMatch(setBadge, /textContent|hidden|getElementById/);
  assert.match(html, /async function refreshOrdersBadge\(\) \{[\s\S]*setOrdersBadge\(0\);[\s\S]*catch \(e\) \{ setOrdersBadge\(0\); \}/);
  assert.doesNotMatch(main, /ordersBadgeMount|ordersBadgeReactApp/);
  assert.match(nav, /import \{ AdminOrdersBadge \} from "\.\/orders-badge\.js"/);
  assert.match(nav, /\{ tab: "orders", label: "Orders", badge: "orders" \}/);
  assert.match(nav, /h\(AdminOrdersBadge, \{ key: "badge" \}\)/);
  assert.match(badge, /export function AdminOrdersBadge/);
  assert.match(badge, /gvdg:admin-orders-badge/);
  assert.match(badge, /window\.__gvdgAdminOrdersBadgeCount/);
  assert.match(badge, /setCount\(Number\(window\.__gvdgAdminOrdersBadgeCount \|\| 0\)\)/);
  assert.match(badge, /className: "orders-badge"/);
  assert.match(badge, /if \(count <= 0\) return null/);
  assert.doesNotMatch(badge, /innerHTML|insertAdjacentHTML|replaceChildren|document\.createElement|querySelector|classList|textContent\s*=|☰|✕|🌙|☀️/);
});

test('admin auth gate is rendered by React from auth state events', () => {
  const html = readFileSync('admin.html', 'utf8');
  const main = readFileSync('src/admin-app/main.js', 'utf8');
  const gate = readFileSync('src/admin-app/auth-gate.js', 'utf8');
  const showPanel = html.match(/function showAdminPanel\(\) \{[\s\S]*?\n        \}/)?.[0];
  const showGate = html.match(/function showGate\(message, withMembersLink\) \{[\s\S]*?\n        \}/)?.[0];

  assert.match(html, /id="adminAuthGateReactApp"/);
  assert.doesNotMatch(html, /id="adminStatus"|id="adminGate"/);
  assert.match(html, /function setAdminAuthGateState\(state\) \{[\s\S]*window\.__gvdgAdminAuthGateState = state;[\s\S]*gvdg:admin-auth-gate/);
  assert.ok(showPanel);
  assert.match(showPanel, /setAdminAuthGateState\(\{ status: 'panel' \}\)/);
  assert.doesNotMatch(showPanel, /adminStatus|adminGate|hidden/);
  assert.ok(showGate);
  assert.match(showGate, /setAdminAuthGateState\(\{ status: 'gate', message, withMembersLink: Boolean\(withMembersLink\) \}\)/);
  assert.doesNotMatch(showGate, /replaceChildren|appendChild|textContent|hidden|adminStatus|adminGate/);
  assert.match(main, /import \{ AdminAuthGate \} from "\.\/auth-gate\.js"/);
  assert.match(main, /const authGateMount = document\.getElementById\("adminAuthGateReactApp"\)/);
  assert.match(main, /createRoot\(authGateMount\)\.render\(h\(AdminAuthGate\)\)/);
  assert.match(gate, /export function AdminAuthGate/);
  assert.match(gate, /data-react-admin-auth-gate/);
  assert.match(gate, /gvdg:admin-auth-gate/);
  assert.match(gate, /window\.__gvdgAdminAuthGateState/);
  assert.match(gate, /setState\(currentState\(\)\)/);
  assert.match(gate, /LockKeyhole/);
  assert.match(gate, /role: "status"/);
  assert.match(gate, /href: "gvdg-members\.html"/);
  assert.match(gate, /if \(state\.status === "panel"\) return null/);
  assert.doesNotMatch(gate, /innerHTML|insertAdjacentHTML|replaceChildren|document\.createElement|querySelector|classList|textContent\s*=|☰|✕|🔒|🌙|☀️/);
});

test('admin navigation is rendered by React and drives legacy pane switching through events', () => {
  const html = readFileSync('admin.html', 'utf8');
  const main = readFileSync('src/admin-app/main.js', 'utf8');
  const nav = readFileSync('src/admin-app/navigation.js', 'utf8');
  const adminSwitch = html.match(/function adminSwitch\(tab\) \{[\s\S]*?if \(tab === 'data-archive'\) adminLoadDataArchiveDestinations\(\);\n        \}/)?.[0];
  const initAdmin = html.match(/function initAdmin\(\) \{[\s\S]*?\$\('adminCreateForm'\)\.addEventListener/)?.[0];

  assert.match(html, /id="adminNavigationReactApp"/);
  assert.doesNotMatch(html, /<nav class="admin-sidebar"|<div class="admin-mobile-nav" role="group"/);
  assert.doesNotMatch(html, /document\.querySelectorAll\('\.admin-tab'\)|document\.querySelectorAll\('\.admin-mnav'\)/);
  assert.ok(adminSwitch);
  assert.match(adminSwitch, /window\.__gvdgAdminActiveTab = tab/);
  assert.match(adminSwitch, /gvdg:admin-active-tab/);
  assert.match(adminSwitch, /document\.querySelectorAll\('\.admin-pane'\)/);
  assert.doesNotMatch(adminSwitch, /\.admin-tab|\.admin-mnav/);
  assert.ok(initAdmin);
  assert.match(initAdmin, /window\.addEventListener\('gvdg:admin-tab-request'/);
  assert.match(initAdmin, /adminSwitch\(tab\)/);
  assert.match(main, /import \{ AdminNavigation \} from "\.\/navigation\.js"/);
  assert.match(main, /const navigationMount = document\.getElementById\("adminNavigationReactApp"\)/);
  assert.match(main, /createRoot\(navigationMount\)\.render\(h\(AdminNavigation\)\)/);
  assert.match(nav, /export const ADMIN_NAV_GROUPS/);
  assert.match(nav, /export function AdminNavigation/);
  assert.match(nav, /className: "admin-mobile-nav"/);
  assert.match(nav, /className: "admin-sidebar"/);
  assert.match(nav, /aria-current/);
  assert.match(nav, /gvdg:admin-tab-request/);
  assert.match(nav, /gvdg:admin-active-tab/);
  assert.match(nav, /window\.__gvdgAdminActiveTab/);
  assert.match(nav, /setActiveTab\(initialTab\(\)\)/);
  assert.match(nav, /value: selectValue\(group\)/);
  assert.doesNotMatch(nav, /innerHTML|insertAdjacentHTML|replaceChildren|document\.createElement|querySelector|classList|textContent\s*=|☰|✕|🔒|🌙|☀️/);
});

test('admin message surface is rendered by React from adminMsg events', () => {
  const html = readFileSync('admin.html', 'utf8');
  const main = readFileSync('src/admin-app/main.js', 'utf8');
  const message = readFileSync('src/admin-app/message.js', 'utf8');
  const adminMsg = html.match(/function adminMsg\(text, ok\) \{[\s\S]*?\n        \}/)?.[0];

  assert.match(html, /id="adminMessageReactApp"/);
  assert.doesNotMatch(html, /id="adminMsg"/);
  assert.match(html, /\.admin-msg\.err \{ color: var\(--over\); \}/);
  assert.match(html, /function setAdminMessageState\(state\) \{[\s\S]*window\.__gvdgAdminMessageState = state;[\s\S]*gvdg:admin-message/);
  assert.ok(adminMsg);
  assert.match(adminMsg, /const message = text \|\| ''/);
  assert.match(adminMsg, /setAdminMessageState\(\{ text: message, ok: message \? ok === true : null \}\)/);
  assert.doesNotMatch(adminMsg, /textContent|className|getElementById|\$\('adminMsg'\)/);
  assert.match(main, /import \{ AdminMessage \} from "\.\/message\.js"/);
  assert.match(main, /const messageMount = document\.getElementById\("adminMessageReactApp"\)/);
  assert.match(main, /createRoot\(messageMount\)\.render\(h\(AdminMessage\)\)/);
  assert.match(message, /export function AdminMessage/);
  assert.match(message, /data-react-admin-message/);
  assert.match(message, /gvdg:admin-message/);
  assert.match(message, /window\.__gvdgAdminMessageState/);
  assert.match(message, /setMessage\(normalizeMessage\(currentMessage\(\)\)\)/);
  assert.match(message, /role = hasText \? \(message\.ok \? "status" : "alert"\) : undefined/);
  assert.match(message, /className: `admin-msg\$\{statusClass\}`/);
  assert.doesNotMatch(message, /innerHTML|insertAdjacentHTML|replaceChildren|document\.createElement|querySelector|classList|textContent\s*=|☰|✕|🔒|🌙|☀️/);
});

test('admin events list is rendered by React from adminLoadEvents state', () => {
  const html = readFileSync('admin.html', 'utf8');
  const main = readFileSync('src/admin-app/main.js', 'utf8');
  const eventsList = readFileSync('src/admin-app/events-list.js', 'utf8');
  const importCandidates = readFileSync('src/admin-app/import-candidates-list.js', 'utf8');
  const adminLoadEvents = html.match(/async function adminLoadEvents\(\) \{[\s\S]*?\n        \}/)?.[0];
  const initAdmin = html.match(/function initAdmin\(\) \{[\s\S]*?\$\('adminCreateForm'\)\.addEventListener/)?.[0];

  assert.match(html, /id="adminEventsListReactApp"/);
  assert.doesNotMatch(html, /id="adminEventsList"/);
  assert.match(html, /function setAdminEventsListState\(state\) \{[\s\S]*window\.__gvdgAdminEventsListState = state;[\s\S]*gvdg:admin-events-list/);
  assert.ok(adminLoadEvents);
  assert.match(adminLoadEvents, /setAdminEventsListState\(\{ status: 'loading', events: \[\] \}\)/);
  assert.match(adminLoadEvents, /setAdminEventsListState\(\{ status: 'ready', events \}\)/);
  assert.doesNotMatch(adminLoadEvents, /adminEventsList|textContent|appendChild|document\.createElement|elx\('div', 'admin-evrow'\)|addEventListener/);
  assert.ok(initAdmin);
  assert.match(initAdmin, /gvdg:admin-event-edit-request/);
  assert.match(initAdmin, /aeEditEvent\(ev\)/);
  assert.match(initAdmin, /gvdg:admin-event-status-request/);
  assert.match(initAdmin, /adminApi\('\/admin\/events\/' \+ ev\.id, \{ method: 'PATCH', body: \{ status \} \}\)/);
  assert.match(initAdmin, /gvdg:admin-event-delete-request/);
  assert.match(initAdmin, /adminApi\('\/admin\/events\/' \+ ev\.id, \{ method: 'DELETE' \}\)/);
  assert.match(initAdmin, /if \(r\.ok\) adminLoadEvents\(\)/);
  assert.match(main, /import \{ AdminEventsList \} from "\.\/events-list\.js"/);
  assert.match(main, /import \{ AdminImportCandidatesList \} from "\.\/import-candidates-list\.js"/);
  assert.match(main, /const eventsListMount = document\.getElementById\("adminEventsListReactApp"\)/);
  assert.match(main, /createRoot\(eventsListMount\)\.render\(h\(AdminEventsList\)\)/);
  assert.match(main, /const importCandidatesMount = document\.getElementById\("adminImportCandidatesReactApp"\)/);
  assert.match(main, /createRoot\(importCandidatesMount\)\.render\(h\(AdminImportCandidatesList\)\)/);
  assert.match(eventsList, /export function AdminEventsList/);
  assert.match(eventsList, /data-react-admin-events-list/);
  assert.match(eventsList, /gvdg:admin-events-list/);
  assert.match(eventsList, /gvdg:admin-event-edit-request/);
  assert.match(eventsList, /gvdg:admin-event-status-request/);
  assert.match(eventsList, /gvdg:admin-event-delete-request/);
  assert.match(eventsList, /window\.__gvdgAdminEventsListState/);
  assert.match(eventsList, /setState\(normalizeState\(currentState\(\)\)\)/);
  assert.match(eventsList, /EVENT_STATUSES = \["scheduled", "live", "final", "cancelled"\]/);
  assert.match(eventsList, /className: "admin-evrow"/);
  assert.match(eventsList, /className: `admin-badge \$\{event\.status\}`/);
  assert.match(eventsList, /role: "status"/);
  assert.doesNotMatch(eventsList, /innerHTML|insertAdjacentHTML|replaceChildren|document\.createElement|querySelector|classList|textContent\s*=|☰|✕|🔒|🌙|☀️/);
  assert.match(importCandidates, /export function AdminImportCandidatesList/);
  assert.match(importCandidates, /gvdg:admin-import-candidates/);
  assert.match(importCandidates, /data-react-admin-import-candidates/);
});

test('admin courses list is rendered by React while legacy code keeps course selects populated', () => {
  const html = readFileSync('admin.html', 'utf8');
  const main = readFileSync('src/admin-app/main.js', 'utf8');
  const coursesList = readFileSync('src/admin-app/courses-list.js', 'utf8');
  const adminLoadCourses = html.match(/async function adminLoadCourses\(\) \{[\s\S]*?\n        \}/)?.[0];

  assert.match(html, /id="adminCoursesListReactApp"/);
  assert.doesNotMatch(html, /id="adminCoursesList"/);
  assert.match(html, /function setAdminCoursesListState\(state\) \{[\s\S]*window\.__gvdgAdminCoursesListState = state;[\s\S]*gvdg:admin-courses-list/);
  assert.ok(adminLoadCourses);
  assert.match(adminLoadCourses, /adminCoursesCache = courses/);
  assert.match(adminLoadCourses, /const sel = \$\('aeCourse'\); sel\.length = 1/);
  assert.match(adminLoadCourses, /const lsel = \$\('alCourse'\); lsel\.length = 1/);
  assert.match(adminLoadCourses, /document\.createElement\('option'\)/);
  assert.match(adminLoadCourses, /setAdminCoursesListState\(\{ courses \}\)/);
  assert.doesNotMatch(adminLoadCourses, /adminCoursesList|list\.textContent|list\.appendChild|elx\('div', 'admin-cand'/);
  assert.match(main, /import \{ AdminCoursesList \} from "\.\/courses-list\.js"/);
  assert.match(main, /const coursesListMount = document\.getElementById\("adminCoursesListReactApp"\)/);
  assert.match(main, /createRoot\(coursesListMount\)\.render\(h\(AdminCoursesList\)\)/);
  assert.match(coursesList, /export function AdminCoursesList/);
  assert.match(coursesList, /data-react-admin-courses-list/);
  assert.match(coursesList, /gvdg:admin-courses-list/);
  assert.match(coursesList, /window\.__gvdgAdminCoursesListState/);
  assert.match(coursesList, /setState\(normalizeState\(currentState\(\)\)\)/);
  assert.match(coursesList, /className: "admin-cand"/);
  assert.doesNotMatch(coursesList, /innerHTML|insertAdjacentHTML|replaceChildren|document\.createElement|querySelector|classList|textContent\s*=|☰|✕|🔒|🌙|☀️/);
});

test('admin club content lists are rendered by React from legacy loader state', () => {
  const html = readFileSync('admin.html', 'utf8');
  const main = readFileSync('src/admin-app/main.js', 'utf8');
  const lists = readFileSync('src/admin-app/club-content-lists.js', 'utf8');
  const adminLoadLeagues = html.match(/async function adminLoadLeagues\(\) \{[\s\S]*?\n        \}/)?.[0];
  const adminLoadFundraisers = html.match(/async function adminLoadFundraisers\(\) \{[\s\S]*?\n        \}/)?.[0];
  const adminLoadMeetings = html.match(/async function adminLoadMeetings\(\) \{[\s\S]*?\n        \}/)?.[0];
  const initAdmin = html.match(/function initAdmin\(\) \{[\s\S]*?\$\('adminCreateForm'\)\.addEventListener/)?.[0];

  assert.match(html, /id="adminLeaguesListReactApp"/);
  assert.match(html, /id="adminFundraisersListReactApp"/);
  assert.match(html, /id="adminMeetingsListReactApp"/);
  assert.doesNotMatch(html, /id="adminLeaguesList"|id="adminFundraisersList"|id="adminMeetingsList"/);
  assert.match(html, /function setAdminLeaguesListState\(state\) \{[\s\S]*window\.__gvdgAdminLeaguesListState = state;[\s\S]*gvdg:admin-leagues-list/);
  assert.match(html, /function setAdminFundraisersListState\(state\) \{[\s\S]*window\.__gvdgAdminFundraisersListState = state;[\s\S]*gvdg:admin-fundraisers-list/);
  assert.match(html, /function setAdminMeetingsListState\(state\) \{[\s\S]*window\.__gvdgAdminMeetingsListState = state;[\s\S]*gvdg:admin-meetings-list/);
  assert.ok(adminLoadLeagues);
  assert.match(adminLoadLeagues, /const sel = \$\('aeLeague'\); sel\.length = 1/);
  assert.match(adminLoadLeagues, /document\.createElement\('option'\)/);
  assert.match(adminLoadLeagues, /setAdminLeaguesListState\(\{ leagues \}\)/);
  assert.doesNotMatch(adminLoadLeagues, /adminLeaguesList|list\.textContent|list\.appendChild|elx\('div', 'admin-evrow'\)|addEventListener/);
  assert.ok(adminLoadFundraisers);
  assert.match(adminLoadFundraisers, /setAdminFundraisersListState\(\{ fundraisers: items \}\)/);
  assert.doesNotMatch(adminLoadFundraisers, /adminFundraisersList|textContent|appendChild|document\.createElement|elx\('div', 'admin-evrow'\)|addEventListener/);
  assert.ok(adminLoadMeetings);
  assert.match(adminLoadMeetings, /setAdminMeetingsListState\(\{ meetings: items \}\)/);
  assert.doesNotMatch(adminLoadMeetings, /adminMeetingsList|textContent|appendChild|document\.createElement|elx\('div', 'admin-evrow'\)|addEventListener/);
  assert.ok(initAdmin);
  assert.match(initAdmin, /gvdg:admin-league-delete-request/);
  assert.match(initAdmin, /adminApi\('\/admin\/leagues\/' \+ league\.id, \{ method: 'DELETE' \}\)/);
  assert.match(initAdmin, /gvdg:admin-fundraiser-status-request/);
  assert.match(initAdmin, /adminApi\('\/admin\/fundraisers\/' \+ fundraiser\.id, \{ method: 'PATCH', body: \{ status \} \}\)/);
  assert.match(initAdmin, /gvdg:admin-fundraiser-delete-request/);
  assert.match(initAdmin, /adminApi\('\/admin\/fundraisers\/' \+ fundraiser\.id, \{ method: 'DELETE' \}\)/);
  assert.match(initAdmin, /gvdg:admin-meeting-delete-request/);
  assert.match(initAdmin, /adminApi\('\/admin\/meetings\/' \+ meeting\.id, \{ method: 'DELETE' \}\)/);
  assert.match(main, /import \{ AdminFundraisersList, AdminLeaguesList, AdminMeetingsList \} from "\.\/club-content-lists\.js"/);
  assert.match(main, /const leaguesListMount = document\.getElementById\("adminLeaguesListReactApp"\)/);
  assert.match(main, /createRoot\(leaguesListMount\)\.render\(h\(AdminLeaguesList\)\)/);
  assert.match(main, /const fundraisersListMount = document\.getElementById\("adminFundraisersListReactApp"\)/);
  assert.match(main, /createRoot\(fundraisersListMount\)\.render\(h\(AdminFundraisersList\)\)/);
  assert.match(main, /const meetingsListMount = document\.getElementById\("adminMeetingsListReactApp"\)/);
  assert.match(main, /createRoot\(meetingsListMount\)\.render\(h\(AdminMeetingsList\)\)/);
  assert.match(lists, /export function AdminLeaguesList/);
  assert.match(lists, /export function AdminFundraisersList/);
  assert.match(lists, /export function AdminMeetingsList/);
  assert.match(lists, /gvdg:admin-leagues-list/);
  assert.match(lists, /gvdg:admin-fundraisers-list/);
  assert.match(lists, /gvdg:admin-meetings-list/);
  assert.match(lists, /gvdg:admin-league-delete-request/);
  assert.match(lists, /gvdg:admin-fundraiser-status-request/);
  assert.match(lists, /gvdg:admin-fundraiser-delete-request/);
  assert.match(lists, /gvdg:admin-meeting-delete-request/);
  assert.match(lists, /data-react-admin-club-list/);
  assert.match(lists, /className: "admin-evrow"/);
  assert.match(lists, /className: "ev-name"/);
  assert.match(lists, /role: "status"/);
  assert.doesNotMatch(lists, /innerHTML|insertAdjacentHTML|replaceChildren|document\.createElement|querySelector|classList|textContent\s*=|☰|✕|🔒|🌙|☀️/);
});

test('admin members list is rendered by React from legacy loader state', () => {
  const html = readFileSync('admin.html', 'utf8');
  const main = readFileSync('src/admin-app/main.js', 'utf8');
  const memberForm = readFileSync('src/admin-app/member-form.js', 'utf8');
  const membersList = readFileSync('src/admin-app/members-list.js', 'utf8');
  const adminLoadMembers = html.match(/async function adminLoadMembers\(\) \{[\s\S]*?\n        \}/)?.[0];
  const adminCreateMember = html.match(/async function adminCreateMemberFromReact\(detail\) \{[\s\S]*?\n        \}/)?.[0];
  const initAdmin = html.match(/function initAdmin\(\) \{[\s\S]*?\$\('adminCreateForm'\)\.addEventListener/)?.[0];

  assert.match(html, /id="adminMemberFormReactApp"/);
  assert.match(html, /id="adminMembersListReactApp"/);
  assert.doesNotMatch(html, /id="adminMemberForm"|id="amName"|id="amPdga"|id="amUdisc"|id="amAdmin"/);
  assert.doesNotMatch(html, /id="adminMembersList"/);
  assert.doesNotMatch(html, /async function adminAddMember\(e\)/);
  assert.match(html, /\.admin-member-form-admin-toggle \{/);
  assert.match(html, /function setAdminMembersListState\(state\) \{[\s\S]*window\.__gvdgAdminMembersListState = state;[\s\S]*gvdg:admin-members-list/);
  assert.ok(adminLoadMembers);
  assert.match(adminLoadMembers, /setAdminMembersListState\(\{ status: 'loading', members: \[\], currentMemberId: ME_ID \}\)/);
  assert.match(adminLoadMembers, /setAdminMembersListState\(\{ status: 'ready', members, currentMemberId: ME_ID \}\)/);
  assert.doesNotMatch(adminLoadMembers, /adminMembersList|list\.textContent|list\.appendChild|elx\('div', 'admin-evrow'\)|addEventListener|document\.createElement/);
  assert.ok(adminCreateMember);
  assert.match(adminCreateMember, /adminApi\('\/admin\/members', \{ method: 'POST', body \}\)/);
  assert.match(adminCreateMember, /gvdg:admin-member-create-result/);
  assert.match(adminCreateMember, /showTempPin\(j\.member, j\.tempPin\)/);
  assert.match(adminCreateMember, /adminLoadMembers\(\)/);
  assert.doesNotMatch(adminCreateMember, /amName|amPdga|amUdisc|amAdmin|\$\('adminMemberForm'\)\.reset/);
  assert.ok(initAdmin);
  assert.match(initAdmin, /gvdg:admin-member-create-request/);
  assert.doesNotMatch(initAdmin, /\$\('adminMemberForm'\)\.addEventListener/);
  assert.match(initAdmin, /gvdg:admin-member-reset-pin-request/);
  assert.match(initAdmin, /adminApi\('\/admin\/members\/reset-pin', \{ method: 'POST', body: \{ identifier \} \}\)/);
  assert.match(initAdmin, /showTempPin\(j\.member, j\.tempPin\)/);
  assert.match(initAdmin, /gvdg:admin-member-role-request/);
  assert.match(initAdmin, /adminApi\('\/admin\/members\/set-role', \{ method: 'POST', body: \{ memberId: member\.memberId, isAdmin: promoting \} \}\)/);
  assert.match(main, /import \{ AdminMemberForm \} from "\.\/member-form\.js"/);
  assert.match(main, /import \{ AdminMembersList, AdminMemberTempPin \} from "\.\/members-list\.js"/);
  assert.match(main, /const memberFormMount = document\.getElementById\("adminMemberFormReactApp"\)/);
  assert.match(main, /createRoot\(memberFormMount\)\.render\(h\(AdminMemberForm\)\)/);
  assert.match(main, /const membersListMount = document\.getElementById\("adminMembersListReactApp"\)/);
  assert.match(main, /createRoot\(membersListMount\)\.render\(h\(AdminMembersList\)\)/);
  assert.match(main, /const memberTempPinMount = document\.getElementById\("adminMemberTempPinReactApp"\)/);
  assert.match(main, /createRoot\(memberTempPinMount\)\.render\(h\(AdminMemberTempPin\)\)/);
  assert.match(memberForm, /export function AdminMemberForm/);
  assert.match(memberForm, /data-react-admin-member-form/);
  assert.match(memberForm, /gvdg:admin-member-create-request/);
  assert.match(memberForm, /gvdg:admin-member-create-result/);
  assert.match(memberForm, /id: "amName"/);
  assert.match(memberForm, /id: "amPdga"/);
  assert.match(memberForm, /id: "amUdisc"/);
  assert.match(memberForm, /id: "amAdmin"/);
  assert.match(memberForm, /className: "admin-member-form-admin-toggle"/);
  assert.match(memberForm, /busy \? "Creating\.\.\." : "Create & issue temp PIN"/);
  assert.doesNotMatch(memberForm, /innerHTML|insertAdjacentHTML|replaceChildren|document\.createElement|querySelector|classList|textContent\s*=|☰|✕|🔒|🌙|☀️|🏆|⚠|⏱|—/);
  assert.match(membersList, /export function AdminMembersList/);
  assert.match(membersList, /gvdg:admin-members-list/);
  assert.match(membersList, /gvdg:admin-member-reset-pin-request/);
  assert.match(membersList, /gvdg:admin-member-role-request/);
  assert.match(membersList, /window\.__gvdgAdminMembersListState/);
  assert.match(membersList, /data-react-admin-members-list/);
  assert.match(membersList, /className: "admin-evrow"/);
  assert.match(membersList, /className: "ev-name"/);
  assert.match(membersList, /role: "status"/);
  assert.doesNotMatch(membersList, /innerHTML|insertAdjacentHTML|replaceChildren|document\.createElement|querySelector|classList|textContent\s*=|☰|✕|🔒|🌙|☀️|🏆|⚠|⏱/);
});

test('admin wallet recent list is rendered by React from legacy loader state', () => {
  const html = readFileSync('admin.html', 'utf8');
  const main = readFileSync('src/admin-app/main.js', 'utf8');
  const walletForm = readFileSync('src/admin-app/wallet-form.js', 'utf8');
  const walletRecent = readFileSync('src/admin-app/wallet-recent-list.js', 'utf8');
  const adminLoadWalletRecent = html.match(/async function adminLoadWalletRecent\(\) \{[\s\S]*?\n        \}/)?.[0];
  const adminPostWalletAdjustment = html.match(/async function adminPostWalletAdjustmentFromReact\(detail\) \{[\s\S]*?\n        \}/)?.[0];
  const initAdmin = html.match(/function initAdmin\(\) \{[\s\S]*?\$\('adminCreateForm'\)\.addEventListener/)?.[0];

  assert.match(html, /id="adminWalletFormReactApp"/);
  assert.match(html, /id="adminWalletRecentReactApp"/);
  assert.doesNotMatch(html, /id="adminWalletForm"|id="waMemberId"|id="waAmount"|id="waNote"/);
  assert.doesNotMatch(html, /id="adminWalletRecent"/);
  assert.doesNotMatch(html, /function walletRow\(tx\)|async function adminPostWalletAdjustment\(e\)/);
  assert.match(html, /\.admin-wallet-form-wide \{/);
  assert.match(html, /function setAdminWalletRecentState\(state\) \{[\s\S]*window\.__gvdgAdminWalletRecentState = state;[\s\S]*gvdg:admin-wallet-recent/);
  assert.ok(adminLoadWalletRecent);
  assert.match(adminLoadWalletRecent, /setAdminWalletRecentState\(\{ status: 'loading', transactions: \[\] \}\)/);
  assert.match(adminLoadWalletRecent, /setAdminWalletRecentState\(\{ status: 'ready', transactions \}\)/);
  assert.doesNotMatch(adminLoadWalletRecent, /adminWalletRecent|replaceChildren|appendChild|walletRow|elx\('p', 'al-note'|document\.createElement|querySelector|classList|textContent\s*=/);
  assert.ok(adminPostWalletAdjustment);
  assert.match(adminPostWalletAdjustment, /adminApi\('\/admin\/wallets\/credit', \{ method: 'POST', body \}\)/);
  assert.match(adminPostWalletAdjustment, /gvdg:admin-wallet-adjustment-result/);
  assert.match(adminPostWalletAdjustment, /adminLoadWalletRecent\(\)/);
  assert.ok(initAdmin);
  assert.match(initAdmin, /gvdg:admin-wallet-adjustment-request/);
  assert.doesNotMatch(initAdmin, /\$\('adminWalletForm'\)\.addEventListener/);
  assert.match(main, /import \{ AdminWalletAdjustmentForm \} from "\.\/wallet-form\.js"/);
  assert.match(main, /import \{ AdminWalletRecentList \} from "\.\/wallet-recent-list\.js"/);
  assert.match(main, /const walletFormMount = document\.getElementById\("adminWalletFormReactApp"\)/);
  assert.match(main, /createRoot\(walletFormMount\)\.render\(h\(AdminWalletAdjustmentForm\)\)/);
  assert.match(main, /const walletRecentMount = document\.getElementById\("adminWalletRecentReactApp"\)/);
  assert.match(main, /createRoot\(walletRecentMount\)\.render\(h\(AdminWalletRecentList\)\)/);
  assert.match(walletForm, /export function AdminWalletAdjustmentForm/);
  assert.match(walletForm, /data-react-admin-wallet-form/);
  assert.match(walletForm, /gvdg:admin-wallet-adjustment-request/);
  assert.match(walletForm, /gvdg:admin-wallet-adjustment-result/);
  assert.match(walletForm, /id: "waMemberId"/);
  assert.match(walletForm, /id: "waAmount"/);
  assert.match(walletForm, /id: "waNote"/);
  assert.match(walletForm, /className: "admin-wallet-form-wide"/);
  assert.match(walletForm, /busy \? "Posting\.\.\." : "Post wallet adjustment"/);
  assert.doesNotMatch(walletForm, /innerHTML|insertAdjacentHTML|replaceChildren|document\.createElement|querySelector|classList|textContent\s*=|☰|✕|🔒|🌙|☀️|🏆|⚠|⏱|—/);
  assert.match(walletRecent, /export function AdminWalletRecentList/);
  assert.match(walletRecent, /gvdg:admin-wallet-recent/);
  assert.match(walletRecent, /window\.__gvdgAdminWalletRecentState/);
  assert.match(walletRecent, /data-react-admin-wallet-recent/);
  assert.match(walletRecent, /className: "wallet-ledger"/);
  assert.match(walletRecent, /className: "wallet-row"/);
  assert.match(walletRecent, /className: "shop-admin-meta"/);
  assert.match(walletRecent, /"credit"/);
  assert.match(walletRecent, /"debit"/);
  assert.match(walletRecent, /role: "status"/);
  assert.doesNotMatch(walletRecent, /innerHTML|insertAdjacentHTML|replaceChildren|document\.createElement|querySelector|classList|textContent\s*=|☰|✕|🔒|🌙|☀️|🏆|⚠|⏱/);
});

test('admin registration CTP, credit, and ace pot widgets are rendered by React from legacy loader state', () => {
  const html = readFileSync('admin.html', 'utf8');
  const main = readFileSync('src/admin-app/main.js', 'utf8');
  const widgets = readFileSync('src/admin-app/registration-widgets.js', 'utf8');
  const rgLoadCtps = html.match(/async function rgLoadCtps\(\) \{[\s\S]*?\n        \}/)?.[0];
  const rgLoadCredits = html.match(/async function rgLoadCredits\(\) \{[\s\S]*?\n        \}/)?.[0];
  const rgLoadAcePot = html.match(/async function rgLoadAcePot\(\) \{[\s\S]*?\n        \}/)?.[0];
  const rgAwardCtpCredit = html.match(/async function rgAwardCtpCredit\(ctp, memberIdValue, winnerNameValue, amountValue\) \{[\s\S]*?\n        \}/)?.[0];
  const initAdmin = html.match(/function initAdmin\(\) \{[\s\S]*?\$\('adminCreateForm'\)\.addEventListener/)?.[0];

  assert.match(html, /id="adminRegistrationCtpsReactApp"/);
  assert.match(html, /id="adminRegistrationCreditsReactApp"/);
  assert.match(html, /id="adminRegistrationAcePotReactApp"/);
  assert.doesNotMatch(html, /id="rgCtpList"|id="rgCreditList"|id="rgAceInfo"/);
  assert.match(html, /function setAdminRegistrationCtpsState\(state\) \{[\s\S]*window\.__gvdgAdminRegistrationCtpsState = state;[\s\S]*gvdg:admin-registration-ctps-list/);
  assert.match(html, /function setAdminRegistrationCreditsState\(state\) \{[\s\S]*window\.__gvdgAdminRegistrationCreditsState = state;[\s\S]*gvdg:admin-registration-credits-list/);
  assert.match(html, /function setAdminRegistrationAcePotState\(state\) \{[\s\S]*window\.__gvdgAdminRegistrationAcePotState = state;[\s\S]*gvdg:admin-registration-ace-pot/);
  assert.ok(rgLoadCtps);
  assert.match(rgLoadCtps, /setAdminRegistrationCtpsState\(\{ status: 'loading', ctps: \[\] \}\)/);
  assert.match(rgLoadCtps, /setAdminRegistrationCtpsState\(\{ status: 'error', ctps: \[\] \}\)/);
  assert.match(rgLoadCtps, /setAdminRegistrationCtpsState\(\{ status: 'ready', ctps \}\)/);
  assert.doesNotMatch(rgLoadCtps, /rgCtpList|replaceChildren|appendChild|document\.createElement|elx\('div', 'admin-evrow'\)|addEventListener|textContent/);
  assert.ok(rgLoadCredits);
  assert.match(rgLoadCredits, /setAdminRegistrationCreditsState\(\{ status: 'loading', payouts: \[\] \}\)/);
  assert.match(rgLoadCredits, /setAdminRegistrationCreditsState\(\{ status: 'error', payouts: \[\] \}\)/);
  assert.match(rgLoadCredits, /setAdminRegistrationCreditsState\(\{ status: 'ready', payouts \}\)/);
  assert.doesNotMatch(rgLoadCredits, /rgCreditList|replaceChildren|appendChild|walletRow|document\.createElement|querySelector|classList|textContent\s*=/);
  assert.ok(rgLoadAcePot);
  assert.match(rgLoadAcePot, /setAdminRegistrationAcePotState\(\{ status: 'loading', acePot: null \}\)/);
  assert.match(rgLoadAcePot, /setAdminRegistrationAcePotState\(\{ status: 'error', acePot: null \}\)/);
  assert.match(rgLoadAcePot, /setAdminRegistrationAcePotState\(\{ status: 'ready', acePot: pot \}\)/);
  assert.doesNotMatch(rgLoadAcePot, /rgAceInfo|textContent|appendChild|document\.createElement/);
  assert.ok(rgAwardCtpCredit);
  assert.match(rgAwardCtpCredit, /String\(memberIdValue \|\| ''\)\.trim\(\)/);
  assert.match(rgAwardCtpCredit, /String\(winnerNameValue \|\| ''\)\.trim\(\)/);
  assert.match(rgAwardCtpCredit, /dollarsToCents\(amountValue\)/);
  assert.doesNotMatch(rgAwardCtpCredit, /memberInput|nameInput|amountInput|\.value/);
  assert.ok(initAdmin);
  assert.match(initAdmin, /gvdg:admin-registration-ctp-winner-request/);
  assert.match(initAdmin, /adminApi\('\/admin\/events\/' \+ rgEventId \+ '\/ctps\/' \+ ctp\.id, \{ method: 'PATCH', body: \{ winner_name: winnerName \|\| null, winner_member_id: winnerMemberId \|\| null \} \}\)/);
  assert.match(initAdmin, /gvdg:admin-registration-ctp-credit-request/);
  assert.match(initAdmin, /rgAwardCtpCredit\(ctp, detail\.winnerMemberId, detail\.winnerName, detail\.amountValue\)/);
  assert.match(initAdmin, /gvdg:admin-registration-ctp-delete-request/);
  assert.match(initAdmin, /adminApi\('\/admin\/events\/' \+ rgEventId \+ '\/ctps\/' \+ ctp\.id, \{ method: 'DELETE' \}\)/);
  assert.match(main, /import \{ AdminRegistrationAcePot, AdminRegistrationCreditsList, AdminRegistrationCtpsList \} from "\.\/registration-widgets\.js"/);
  assert.match(main, /const registrationCtpsMount = document\.getElementById\("adminRegistrationCtpsReactApp"\)/);
  assert.match(main, /createRoot\(registrationCtpsMount\)\.render\(h\(AdminRegistrationCtpsList\)\)/);
  assert.match(main, /const registrationCreditsMount = document\.getElementById\("adminRegistrationCreditsReactApp"\)/);
  assert.match(main, /createRoot\(registrationCreditsMount\)\.render\(h\(AdminRegistrationCreditsList\)\)/);
  assert.match(main, /const registrationAcePotMount = document\.getElementById\("adminRegistrationAcePotReactApp"\)/);
  assert.match(main, /createRoot\(registrationAcePotMount\)\.render\(h\(AdminRegistrationAcePot\)\)/);
  assert.match(widgets, /export function AdminRegistrationCtpsList/);
  assert.match(widgets, /export function AdminRegistrationCreditsList/);
  assert.match(widgets, /export function AdminRegistrationAcePot/);
  assert.match(widgets, /gvdg:admin-registration-ctps-list/);
  assert.match(widgets, /gvdg:admin-registration-credits-list/);
  assert.match(widgets, /gvdg:admin-registration-ace-pot/);
  assert.match(widgets, /gvdg:admin-registration-ctp-winner-request/);
  assert.match(widgets, /gvdg:admin-registration-ctp-credit-request/);
  assert.match(widgets, /gvdg:admin-registration-ctp-delete-request/);
  assert.match(widgets, /window\.__gvdgAdminRegistrationCtpsState/);
  assert.match(widgets, /window\.__gvdgAdminRegistrationCreditsState/);
  assert.match(widgets, /window\.__gvdgAdminRegistrationAcePotState/);
  assert.match(widgets, /data-react-admin-registration-ctps/);
  assert.match(widgets, /data-react-admin-registration-credits/);
  assert.match(widgets, /data-react-admin-registration-ace-pot/);
  assert.match(widgets, /className: "admin-evrow"/);
  assert.match(widgets, /className: "wallet-ledger"/);
  assert.match(widgets, /role: "status"/);
  assert.match(widgets, /role: "alert"/);
  assert.doesNotMatch(widgets, /innerHTML|insertAdjacentHTML|replaceChildren|document\.createElement|querySelector|classList|textContent\s*=|☰|✕|🌙|☀️|🏆|⚠|⏱/);
});

test('admin product inventory list is rendered by React from legacy loader state', () => {
  const html = readFileSync('admin.html', 'utf8');
  const main = readFileSync('src/admin-app/main.js', 'utf8');
  const productForm = readFileSync('src/admin-app/product-form.js', 'utf8');
  const productsList = readFileSync('src/admin-app/products-list.js', 'utf8');
  const adminLoadProducts = html.match(/async function adminLoadProducts\(\) \{[\s\S]*?\n        \}/)?.[0];
  const adminCreateProduct = html.match(/async function adminCreateProductFromReact\(detail\) \{[\s\S]*?\n        \}/)?.[0];
  const initAdmin = html.match(/function initAdmin\(\) \{[\s\S]*?\$\('adminCreateForm'\)\.addEventListener/)?.[0];

  assert.match(html, /id="adminProductFormReactApp"/);
  assert.match(html, /id="adminProductsListReactApp"/);
  assert.doesNotMatch(html, /id="adminProductForm"/);
  assert.doesNotMatch(html, /id="adminProductsList"/);
  assert.doesNotMatch(html, /id="psImagePreview"|function adminAddProduct|function onProductImageFile|function resizeImageToDataUrl|productImageDataUrl|adminProductImagePreviewReactApp|gvdg:admin-product-image-preview/);
  assert.match(html, /\.shop-admin-thumb\.fallback/);
  assert.match(html, /function setAdminProductsListState\(state\) \{[\s\S]*window\.__gvdgAdminProductsListState = state;[\s\S]*gvdg:admin-products-list/);
  assert.ok(adminLoadProducts);
  assert.match(adminLoadProducts, /setAdminProductsListState\(\{ status: 'loading', products: \[\], inventoryStatus:/);
  assert.match(adminLoadProducts, /setAdminProductsListState\(\{ status: 'ready', products, inventoryStatus: status \}\)/);
  assert.match(adminLoadProducts, /adminApi\('\/admin\/shop\/products\?' \+ params\.toString\(\)\)/);
  assert.doesNotMatch(adminLoadProducts, /adminProductsList|replaceChildren|appendChild|productThumb|shop-admin-row|document\.createElement|querySelector|classList|textContent\s*=/);
  assert.doesNotMatch(html, /function productThumb|function productIsActive/);
  assert.ok(adminCreateProduct);
  assert.match(adminCreateProduct, /adminApi\('\/admin\/shop\/products', \{ method: 'POST', body \}\)/);
  assert.match(adminCreateProduct, /gvdg:admin-product-create-result/);
  assert.match(adminCreateProduct, /adminLoadProducts\(\)/);
  assert.ok(initAdmin);
  assert.match(initAdmin, /gvdg:admin-product-create-request/);
  assert.match(initAdmin, /gvdg:admin-product-photo-ready/);
  assert.match(initAdmin, /gvdg:admin-product-photo-error/);
  assert.doesNotMatch(initAdmin, /\$\('adminProductForm'\)\.addEventListener|\$\('psImageFile'\)\.addEventListener|\$\('psImage'\)\.addEventListener/);
  assert.match(initAdmin, /gvdg:admin-product-save-request/);
  assert.match(initAdmin, /adminApi\('\/admin\/shop\/products\/' \+ product\.id, \{ method: 'PATCH', body: \{ price_cents: dollarsToCents\(detail\.priceValue\), stock_qty: parseInt\(detail\.stockValue, 10\) \|\| 0, active: detail\.active === true \} \}\)/);
  assert.match(initAdmin, /gvdg:admin-product-delete-request/);
  assert.match(initAdmin, /adminApi\('\/admin\/shop\/products\/' \+ product\.id, \{ method: 'DELETE' \}\)/);
  assert.match(main, /import \{ AdminProductForm \} from "\.\/product-form\.js"/);
  assert.match(main, /import \{ AdminProductsList \} from "\.\/products-list\.js"/);
  assert.match(main, /const productsListMount = document\.getElementById\("adminProductsListReactApp"\)/);
  assert.match(main, /createRoot\(productsListMount\)\.render\(h\(AdminProductsList\)\)/);
  assert.match(main, /const productFormMount = document\.getElementById\("adminProductFormReactApp"\)/);
  assert.match(main, /createRoot\(productFormMount\)\.render\(h\(AdminProductForm\)\)/);
  assert.match(productForm, /export function AdminProductForm/);
  assert.match(productForm, /data-react-admin-product-form/);
  assert.match(productForm, /gvdg:admin-product-create-request/);
  assert.match(productForm, /gvdg:admin-product-create-result/);
  assert.match(productForm, /gvdg:admin-product-photo-ready/);
  assert.match(productForm, /gvdg:admin-product-photo-error/);
  assert.match(productForm, /data-react-admin-product-image-preview/);
  assert.match(productForm, /function resizeImageToDataUrl/);
  assert.match(productForm, /document\.createElement\("canvas"\)/);
  assert.match(productForm, /alt: "Selected product preview"/);
  assert.match(productForm, /className: "admin-product-image-preview"/);
  assert.match(productForm, /className: "admin-product-form-wide"/);
  assert.doesNotMatch(productForm, /innerHTML|insertAdjacentHTML|replaceChildren|querySelector|classList|textContent\s*=|☰|✕|🔒|🌙|☀️|🏆|⚠|⏱|—/);
  assert.match(productsList, /export function AdminProductsList/);
  assert.doesNotMatch(productsList, /AdminProductImagePreview|gvdg:admin-product-image-preview|__gvdgAdminProductImagePreviewState/);
  assert.match(productsList, /gvdg:admin-products-list/);
  assert.match(productsList, /gvdg:admin-product-save-request/);
  assert.match(productsList, /gvdg:admin-product-delete-request/);
  assert.match(productsList, /window\.__gvdgAdminProductsListState/);
  assert.match(productsList, /data-react-admin-products-list/);
  assert.match(productsList, /className: "shop-admin-list"/);
  assert.match(productsList, /className: `shop-admin-row/);
  assert.match(productsList, /className: "shop-admin-thumb"/);
  assert.match(productsList, /className: "shop-admin-thumb fallback"/);
  assert.match(productsList, /className: "shop-admin-controls"/);
  assert.match(productsList, /role: "status"/);
  assert.doesNotMatch(productsList, /innerHTML|insertAdjacentHTML|replaceChildren|document\.createElement|querySelector|classList|textContent\s*=|☰|✕|🔒|🌙|☀️|🏆|⚠|⏱/);
});

test('admin orders list is rendered by React from legacy loader state', () => {
  const html = readFileSync('admin.html', 'utf8');
  const main = readFileSync('src/admin-app/main.js', 'utf8');
  const ordersList = readFileSync('src/admin-app/orders-list.js', 'utf8');
  const adminLoadOrders = html.match(/async function adminLoadOrders\(\) \{[\s\S]*?\n        \}/)?.[0];
  const saveOrder = html.match(/async function saveOrder\(id, body\) \{[\s\S]*?\n        \}/)?.[0];
  const cancelOrder = html.match(/async function cancelOrder\(id, status\) \{[\s\S]*?\n        \}/)?.[0];
  const deleteOrder = html.match(/async function deleteOrder\(id\) \{[\s\S]*?\n        \}/)?.[0];
  const initAdmin = html.match(/function initAdmin\(\) \{[\s\S]*?\$\('adminCreateForm'\)\.addEventListener/)?.[0];

  assert.match(html, /id="adminOrdersListReactApp"/);
  assert.doesNotMatch(html, /id="adminOrdersList"/);
  assert.doesNotMatch(html, /function orderCard|const ORDER_STATUS_LABELS|const ORDER_UNFULFILLED/);
  assert.match(html, /function setAdminOrdersListState\(state\) \{[\s\S]*window\.__gvdgAdminOrdersListState = state;[\s\S]*gvdg:admin-orders-list/);
  assert.ok(adminLoadOrders);
  assert.match(adminLoadOrders, /setAdminOrdersListState\(\{ status: 'loading', orders: \[\], filterStatus: status \}\)/);
  assert.match(adminLoadOrders, /setAdminOrdersListState\(\{ status: 'error', orders: \[\], filterStatus: status \}\)/);
  assert.match(adminLoadOrders, /setAdminOrdersListState\(\{ status: 'ready', orders, filterStatus: status \}\)/);
  assert.match(adminLoadOrders, /adminApi\('\/admin\/orders' \+ \(status \? '\?status=' \+ encodeURIComponent\(status\) : ''\)\)/);
  assert.match(adminLoadOrders, /setOrdersBadge\(unfulfilled\)/);
  assert.doesNotMatch(adminLoadOrders, /\$\('adminOrdersList'\)|replaceChildren|appendChild|orderCard|document\.createElement|querySelector|classList|textContent\s*=|addEventListener/);
  assert.ok(saveOrder);
  assert.match(saveOrder, /adminApi\('\/admin\/orders\/' \+ id, \{ method: 'PATCH', body \}\)/);
  assert.match(saveOrder, /adminLoadOrders\(\); return true/);
  assert.match(saveOrder, /return false/);
  assert.ok(cancelOrder);
  assert.match(cancelOrder, /if \(status === 'cancelled'\) return false/);
  assert.match(cancelOrder, /return saveOrder\(id, \{ status: 'cancelled' \}\)/);
  assert.doesNotMatch(cancelOrder, /confirm/);
  assert.ok(deleteOrder);
  assert.match(deleteOrder, /adminApi\('\/admin\/orders\/' \+ id, \{ method: 'DELETE' \}\)/);
  assert.match(deleteOrder, /adminLoadOrders\(\); return true/);
  assert.match(deleteOrder, /return false/);
  assert.doesNotMatch(deleteOrder, /confirm/);
  assert.ok(initAdmin);
  assert.match(initAdmin, /gvdg:admin-order-save-request/);
  assert.match(initAdmin, /const trackingCarrier = String\(detail\.trackingCarrier \|\| ''\)\.trim\(\)/);
  assert.match(initAdmin, /const trackingNumber = String\(detail\.trackingNumber \|\| ''\)\.trim\(\)/);
  assert.match(initAdmin, /tracking_carrier: trackingCarrier \|\| null/);
  assert.match(initAdmin, /tracking_number: trackingNumber \|\| null/);
  assert.match(initAdmin, /gvdg:admin-order-cancel-request/);
  assert.match(initAdmin, /cancelOrder\(order\.id, order\.status\)/);
  assert.match(initAdmin, /gvdg:admin-order-delete-request/);
  assert.match(initAdmin, /deleteOrder\(order\.id\)/);
  assert.match(initAdmin, /gvdg:admin-order-action-result/);
  assert.match(main, /import \{ AdminOrdersList \} from "\.\/orders-list\.js"/);
  assert.match(main, /const ordersListMount = document\.getElementById\("adminOrdersListReactApp"\)/);
  assert.match(main, /createRoot\(ordersListMount\)\.render\(h\(AdminOrdersList\)\)/);
  assert.match(ordersList, /export function AdminOrdersList/);
  assert.match(ordersList, /gvdg:admin-orders-list/);
  assert.match(ordersList, /gvdg:admin-order-save-request/);
  assert.match(ordersList, /gvdg:admin-order-cancel-request/);
  assert.match(ordersList, /gvdg:admin-order-delete-request/);
  assert.match(ordersList, /gvdg:admin-order-action-result/);
  assert.match(ordersList, /window\.__gvdgAdminOrdersListState/);
  assert.match(ordersList, /data-react-admin-orders-list/);
  assert.match(ordersList, /className: "orders-list"/);
  assert.match(ordersList, /className: "order-head"/);
  assert.match(ordersList, /className: "order-items"/);
  assert.match(ordersList, /className: "order-controls"/);
  assert.match(ordersList, /className: "order-actions"/);
  assert.match(ordersList, /role: "status"/);
  assert.match(ordersList, /role: "alert"/);
  assert.doesNotMatch(ordersList, /innerHTML|insertAdjacentHTML|replaceChildren|document\.createElement|querySelector|classList|textContent\s*=|☰|✕|🔒|🌙|☀️|🏆|⚠|⏱/);
});

test('admin data archive destination list is rendered by React from legacy loader state', () => {
  const html = readFileSync('admin.html', 'utf8');
  const main = readFileSync('src/admin-app/main.js', 'utf8');
  const destinationForm = readFileSync('src/admin-app/data-archive-destination-form.js', 'utf8');
  const destinationsList = readFileSync('src/admin-app/data-archive-destinations-list.js', 'utf8');
  const adminLoadDataArchiveDestinations = html.match(/async function adminLoadDataArchiveDestinations\(\) \{[\s\S]*?\n        \}/)?.[0];
  const adminSaveDataArchiveEndpoint = html.match(/async function adminSaveDataArchiveEndpointFromReact\(detail\) \{[\s\S]*?async function adminRunArchiveExport/)?.[0];
  const editDataArchiveDestination = html.match(/function editDataArchiveDestination\(destination\) \{[\s\S]*?\n        \}/)?.[0];
  const initAdmin = html.match(/function initAdmin\(\) \{[\s\S]*?\$\('adminCreateForm'\)\.addEventListener/)?.[0];

  assert.match(html, /id="adminDataArchiveDestinationFormReactApp"/);
  assert.match(html, /id="adminDataArchiveDestinationsReactApp"/);
  assert.doesNotMatch(html, /id="dxEndpointForm"|id="dxEndpointId"|id="dxEndpointLabel"|id="dxEndpointUrl"|id="dxAuthHeader"|id="dxAuthPrefix"|id="dxAuthToken"|id="dxAuthTokenClear"|id="dxEndpointActive"|id="dxEndpointSave"|id="dxEndpointCancel"/);
  assert.doesNotMatch(html, /id="dxDestinationsList"/);
  assert.doesNotMatch(html, /function resetDataArchiveEndpointForm|async function adminSaveDataArchiveEndpoint\(e\)/);
  assert.match(html, /function setAdminDataArchiveDestinationsState\(state\) \{[\s\S]*window\.__gvdgAdminDataArchiveDestinationsState = state;[\s\S]*gvdg:admin-data-archive-destinations-list/);
  assert.ok(adminLoadDataArchiveDestinations);
  assert.match(adminLoadDataArchiveDestinations, /setAdminDataArchiveDestinationsState\(\{ status: 'loading', destinations: \[\] \}\)/);
  assert.match(adminLoadDataArchiveDestinations, /setAdminDataArchiveDestinationsState\(\{ status: 'error', destinations: \[\] \}\)/);
  assert.match(adminLoadDataArchiveDestinations, /setAdminDataArchiveDestinationsState\(\{ status: 'ready', destinations \}\)/);
  assert.match(adminLoadDataArchiveDestinations, /select\.replaceChildren\(\)/);
  assert.doesNotMatch(adminLoadDataArchiveDestinations, /dxDestinationsList|list\.|elx\('p', 'al-note'|elx\('div', 'admin-evrow'\)|left\.appendChild|controls\.appendChild|addEventListener/);
  assert.ok(editDataArchiveDestination);
  assert.match(editDataArchiveDestination, /setDataArchiveEndpointForm\(destination\)/);
  assert.match(html, /function setDataArchiveEndpointForm\(destination\) \{[\s\S]*gvdg:admin-data-archive-destination-form-edit/);
  assert.ok(adminSaveDataArchiveEndpoint);
  assert.match(adminSaveDataArchiveEndpoint, /adminApi\(path, \{ method, body \}\)/);
  assert.match(adminSaveDataArchiveEndpoint, /gvdg:admin-data-archive-destination-save-result/);
  assert.match(adminSaveDataArchiveEndpoint, /detail: \{ ok: false, requestId, message \}/);
  assert.match(adminSaveDataArchiveEndpoint, /adminLoadDataArchiveDestinations\(\)/);
  assert.doesNotMatch(adminSaveDataArchiveEndpoint, /dxEndpointLabel|dxEndpointUrl|dxAuthHeader|dxAuthPrefix|dxAuthToken|dxAuthTokenClear|dxEndpointActive|\$\('dxEndpoint/);
  assert.ok(initAdmin);
  assert.doesNotMatch(initAdmin, /\$\('dxEndpointForm'\)\.addEventListener|\$\('dxEndpointCancel'\)\.addEventListener/);
  assert.match(initAdmin, /gvdg:admin-data-archive-destination-edit-request/);
  assert.match(initAdmin, /editDataArchiveDestination\(destination\)/);
  assert.match(initAdmin, /gvdg:admin-data-archive-destination-save-request/);
  assert.match(initAdmin, /adminSaveDataArchiveEndpointFromReact\(event\.detail \|\| \{\}\)/);
  assert.match(initAdmin, /gvdg:admin-data-archive-destination-activate-request/);
  assert.match(initAdmin, /adminApi\('\/admin\/export\/endpoints\/' \+ destination\.id \+ '\/activate', \{ method: 'POST' \}\)/);
  assert.match(initAdmin, /gvdg:admin-data-archive-destination-delete-request/);
  assert.match(initAdmin, /adminApi\('\/admin\/export\/endpoints\/' \+ destination\.id, \{ method: 'DELETE' \}\)/);
  assert.match(main, /import \{ AdminDataArchiveDestinationForm \} from "\.\/data-archive-destination-form\.js"/);
  assert.match(main, /import \{ AdminDataArchiveDestinationsList, AdminDataArchiveExportResult \} from "\.\/data-archive-destinations-list\.js"/);
  assert.match(main, /const dataArchiveDestinationFormMount = document\.getElementById\("adminDataArchiveDestinationFormReactApp"\)/);
  assert.match(main, /createRoot\(dataArchiveDestinationFormMount\)\.render\(h\(AdminDataArchiveDestinationForm\)\)/);
  assert.match(main, /const dataArchiveDestinationsMount = document\.getElementById\("adminDataArchiveDestinationsReactApp"\)/);
  assert.match(main, /createRoot\(dataArchiveDestinationsMount\)\.render\(h\(AdminDataArchiveDestinationsList\)\)/);
  assert.match(destinationForm, /export function AdminDataArchiveDestinationForm/);
  assert.match(destinationForm, /formRef = React\.useRef\(null\)/);
  assert.match(destinationForm, /const \[notice, setNotice\] = React\.useState\(""\)/);
  assert.match(destinationForm, /data-react-admin-data-archive-destination-form/);
  assert.match(destinationForm, /gvdg:admin-data-archive-destination-form-edit/);
  assert.match(destinationForm, /gvdg:admin-data-archive-destination-save-request/);
  assert.match(destinationForm, /gvdg:admin-data-archive-destination-save-result/);
  assert.match(destinationForm, /scrollIntoView\(\{ block: "start" \}\)/);
  assert.match(destinationForm, /className: "admin-form admin-data-archive-destination-form"/);
  assert.match(destinationForm, /className: "al-note err"/);
  assert.match(destinationForm, /role: "alert"/);
  assert.match(destinationForm, /id: "dxEndpointLabel"/);
  assert.match(destinationForm, /id: "dxEndpointUrl"/);
  assert.match(destinationForm, /id: "dxAuthHeader"/);
  assert.match(destinationForm, /id: "dxAuthPrefix"/);
  assert.match(destinationForm, /id: "dxAuthToken"/);
  assert.match(destinationForm, /id: "dxAuthTokenClear"/);
  assert.match(destinationForm, /id: "dxEndpointActive"/);
  assert.match(destinationForm, /hasAuthToken === true \|\| destination\.has_auth_token === true/);
  assert.match(destinationForm, /form\.hasAuthToken \? "Leave blank to keep existing token" : "Add a token \(optional\)"/);
  assert.match(destinationForm, /busy \? "Saving\.\.\." : form\.id \? "Save destination" : "Add destination"/);
  assert.match(destinationForm, /className: "register-addon admin-data-archive-destination-toggle"/);
  assert.match(destinationForm, /className: "admin-form-actions"/);
  assert.match(html, /\.admin-data-archive-destination-form \{ scroll-margin-top: 5\.5rem; \}/);
  assert.match(html, /\.admin-form \.admin-data-archive-destination-toggle \{/);
  assert.doesNotMatch(destinationForm, /innerHTML|insertAdjacentHTML|replaceChildren|document\.createElement|querySelector|classList|textContent\s*=|☰|✕|🔒|🌙|☀️|🏆|⚠|⏱|—/);
  assert.match(destinationsList, /export function AdminDataArchiveDestinationsList/);
  assert.match(destinationsList, /gvdg:admin-data-archive-destinations-list/);
  assert.match(destinationsList, /gvdg:admin-data-archive-destination-edit-request/);
  assert.match(destinationsList, /gvdg:admin-data-archive-destination-activate-request/);
  assert.match(destinationsList, /gvdg:admin-data-archive-destination-delete-request/);
  assert.match(destinationsList, /window\.__gvdgAdminDataArchiveDestinationsState/);
  assert.match(destinationsList, /data-react-admin-data-archive-destinations/);
  assert.match(destinationsList, /className: "admin-evrow"/);
  assert.match(destinationsList, /className: "ev-name"/);
  assert.match(destinationsList, /className: "shop-admin-controls"/);
  assert.match(destinationsList, /className: "admin-msg ok"/);
  assert.match(destinationsList, /role: "status"/);
  assert.match(destinationsList, /role: "alert"/);
  assert.doesNotMatch(destinationsList, /innerHTML|insertAdjacentHTML|replaceChildren|document\.createElement|querySelector|classList|textContent\s*=|☰|✕|🔒|🌙|☀️|🏆|⚠|⏱/);
});
